name: continuous integration

on: push

env:
  KNOTS_VERSION: '29.3.knots20260210'
  PYTHON_VERSION: '3.11'

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: |
          bash .github/scripts/install-knots.sh
          bitcoind -regtest -deprecatedrpc=create_bdb &
      - run: |
          python -m venv venv
          echo "venv/bin" >> $GITHUB_PATH
          source venv/bin/activate
          pip install pip-tools
          pip-compile --strip-extras --extra dev
          pip-sync
      - run: bitcoin-cli -regtest -named createwallet wallet_name=testing descriptors=false
      - run: |
          python examples/p2wpkh.py
          python main.py &
          echo $! > server.pid
      - run: |
          python examples/raffle0.py
          python examples/raffle1.py
          pytest
      - if: ${{ always() }}
        run: |
          bitcoin-cli -regtest stop
          kill $(cat server.pid)
