name: continuous integration

on: push

env:
  KNOTS_VERSION: '27.1.knots20240801'
  PYTHON_VERSION: '3.11'

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: |
          bash .github/scripts/install-knots.sh
          bitcoind -regtest -deprecatedrpc=create_bdb &
      - run: |
          python -m venv venv
          echo "venv/bin" >> $GITHUB_PATH
          source venv/bin/activate
          pip install pip-tools
          pip-compile --strip-extras --extra dev
          pip-sync
      - run: bitcoin-cli -regtest -named createwallet wallet_name=testing descriptors=false
      - run: |
          python examples/p2wpkh.py
          python main.py &
          echo $! > server.pid
      - run: pytest
      - if: ${{ always() }}
        run: |
          bitcoin-cli -regtest stop
          kill $(cat server.pid)
